name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  iOS:
    name: iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup iOS Certificates
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERT_P12 }}
          p12-password: ${{ secrets.P12_PASS }}
          keychain: github-actions-xamarin
          keychain-password: ''
          
      - uses: bradyjoslin/xamarinios-signedbuild-action@v1
        with:
          csproj_path: TestGitAction/TestGitAction/TestGitAction.csproj
          mobileprovision: ${{ secrets.MOBILEPROVISION }}
          cert_p12: ${{ secrets.CERT_P12 }}
          p12_pass: ${{ secrets.P12_PASS }}
          configuration: "Release"
          mono_version: "preview"
          xamarin_ios_version: "preview"
      - uses: actions/upload-artifact@v2
        with:
          name: ipa
          path: TestGitAction/TestGitAction/bin/iPhone/Release/TestGitAction.ipa
